[build]
builder = "nixpacks"
buildCommand = "./gradlew bootJar -x test"

[deploy]
startCommand = "java -jar build/libs/rentflow-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
restartPolicyType = "on_failure"

[[services]]
name = "rentflow"

[services.variables]
SPRING_DATASOURCE_URL = "${{Postgres.DATABASE_URL}}"
APP_JWT_SECRET = "${{JWT_SECRET}}"
APP_JWT_EXPIRATION_MS = "86400000"
